os:
    - windows
language: c++
jobs:
    include:
        - name: "Python and VS Setup"
          os: windows          
          language: shell 
          before_install:
              - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
              - choco install python --version 3.9.0
              - python -m pip install --upgrade pip
          env:
            - PATH=/c/Python39:/c/Python39/Scripts:$PATH
script:
    - ./build.bat debug release
    - ./t2-output/win64-msvc-debug-default/coalpy_tests.exe -s core,tasksystem
