os:
    - windows
language: c++
jobs:
    include:
        - name: "Python and VS Setup"
          os: windows          
          language: shell 
          before_install:
              - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
              - choco install python --version 3.9.0
              - python -m pip install --upgrade pip
          env:
            - PATH=/c/Python39:/c/Python39/Scripts:$PATH
            - PYTHON39_ROOT=/c/Python39
script:
    - ./build.bat
