name: coalpy-continuous-integration
run-name: CI - ${{ github.actor }}
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo content
          uses: actions/checkout@v2 # checkout the repository content to github runner
        - name: setup python
          uses: actions/setup-python@v4 
          with:
            python-version: '3.10'
        - name: set branch
          run: echo "CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
        - name: create session
          env:
            CIIP: ${{secrets.ciip }}
            CIPORT: ${{secrets.ciport }}
          run: python .github/scripts/agent.py -s $CIIP -p $CIPORT session_start s=0 > session
        - name: remote git sync
          env:
            CIIP: ${{secrets.ciip }}
            CIPORT: ${{secrets.ciport }}
          run: python .github/scripts/agent.py -s $CIIP -p $CIPORT git session=$(cat session)&op=sync&branch=$CURRENT_BRANCH
        - name: run build
          env:
            CIIP: ${{secrets.ciip }}
            CIPORT: ${{secrets.ciport }}
          run: |
            export SESSION=$(cat session) && python .github/scripts/agent.py -s $CIIP -p $CIPORT build "session=$(cat session)" -w
        - name: destroy session
          env:
            CIIP: ${{secrets.ciip }}
            CIPORT: ${{secrets.ciport }}
          run: python .github/scripts/agent.py -s $CIIP -p $CIPORT session_end session=$(cat session)
