name: coalpy-continuous-integration
run-name: CI - ${{ github.actor }}
on: [push]
jobs:
    build-debug:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - uses: .github/workflows/build.yaml
              with:
                build_type: "debug"

